chunk_size: 128
local_cpu: true
enable_async_loading: true
storage_plugins:
- daosgds
extra_config:
  storage_plugin.daosgds.module_path: lmcache_daos.staging_probe_backend
  storage_plugin.daosgds.class_name: ProbeBackend
  daosgds.pool: discospool
  daosgds.container: kvcache
  daosgds.transport: object
  daosgds.root: /minji-discovery-live-687cb9edd9124ecc9b107bc0de8fc71c
  daosgds.object_namespace: 'minji-discovery-live-687cb9edd9124ecc9b107bc0de8fc71c:'
  daosgds.object_library: /root/discos_minji/libdaosgdr.so
  daosgds.gpu_buffer_gb: 10
  daosgds.io_workers: 16
  daosgds.meta_workers: 16
  daosgds.store: true
  daosgds.cpu_prefetch_gpu_gb: 5
  daosgds.probe_interval_ms: 20
max_local_cpu_size: 8.0
use_layerwise: false
store_location: null
